<a href="https://colab.research.google.com/github/viklearnsai-hub/Machine_Learning/blob/main/Telecom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
!pip install  tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.18.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.11.12)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.4)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [44]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [45]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [46]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [47]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [48]:
X = df.iloc[:,1:18]

In [34]:
X.head(1)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check

In [49]:
Y= df.iloc[:,20]

In [50]:
Y.head(1)

0    No
Name: Churn, dtype: object

In [53]:
X_encoded = pd.get_dummies( X, drop_first=True ,dtype=int)

In [54]:
X_encoded.head(10)

,SeniorCitizen,tenure,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,1,0
1,0,34,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,2,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
3,0,45,1,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,2,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
5,0,8,0,0,0,1,0,1,1,0,...,0,1,0,1,0,0,1,0,1,0
6,0,22,1,0,1,1,0,1,1,0,...,0,1,0,0,0,0,1,1,0,0
7,0,10,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8,0,28,0,1,0,1,0,1,1,0,...,0,1,0,1,0,0,1,0,1,0
9,0,62,1,0,1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [17]:
parnterDummies = pd.get_dummies(X['Partner'],dtype=int,drop_first=True)

In [22]:
phoneServiceDummy = pd.get_dummies(X['PhoneService'],dtype=int,drop_first=True)

In [27]:
multiPhonesDummy = pd.get_dummies(X['MultipleLines'],dtype=int,drop_first=True)

Index(['customerID', '**gender**', 'SeniorCitizen', '**Partner**', '**Dependents**',
       'tenure', '**PhoneService**', '**MultipleLines**', '**InternetService**',
       '**OnlineSecurity**', '**OnlineBackup**', '**DeviceProtection**', '**TechSupport**',
       '**StreamingTV**', '**StreamingMovies**', '**Contract**', '**PaperlessBilling**',
       '**PaymentMethod**', '**MonthlyCharges**', 'TotalCharges', 'Churn'],
      dtype='object')

In [37]:
genderDummy = pd.get_dummies(X['gender'],dtype=int,drop_first=True)
parnterDummies = pd.get_dummies(X['Partner'],dtype=int,drop_first=True)
dependentDummies = pd.get_dummies(X['Dependents'],dtype=int,drop_first=True)
phoneServiceDummy = pd.get_dummies(X['PhoneService'],dtype=int,drop_first=True)
multiPhonesDummy = pd.get_dummies(X['MultipleLines'],dtype=int,drop_first=True)
internetServiceDummy = pd.get_dummies(X['InternetService'],dtype=int,drop_first=True)
onlineSecurityDummy = pd.get_dummies(X['OnlineSecurity'],dtype=int,drop_first=True)
onlineBackupDummy = pd.get_dummies(X['OnlineBackup'],dtype=int,drop_first=True)
deviceProtectionDummy = pd.get_dummies(X['DeviceProtection'],dtype=int,drop_first=True)
techSupportDummy = pd.get_dummies(X['TechSupport'],dtype=int,drop_first=True)
streamingTVDummy = pd.get_dummies(X['StreamingTV'],dtype=int,drop_first=True)
streamingMoviesDummy = pd.get_dummies(X['StreamingMovies'],dtype=int,drop_first=True)
contractDummy = pd.get_dummies(X['Contract'],dtype=int,drop_first=True)
paperlessBillingDummy = pd.get_dummies(X['PaperlessBilling'],dtype=int,drop_first=True)
paymentMethodDummy = pd.get_dummies(X['PaymentMethod'],dtype=int,drop_first=True)

In [38]:
X= X.drop(['gender','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaperlessBilling','PaymentMethod'],axis=1)

In [39]:
X = pd.concat([X,genderDummy,parnterDummies,dependentDummies,phoneServiceDummy,multiPhonesDummy,internetServiceDummy,onlineSecurityDummy,onlineBackupDummy,deviceProtectionDummy,techSupportDummy,streamingTVDummy,streamingMoviesDummy,contractDummy,paperlessBillingDummy,paymentMethodDummy],axis=1)

In [42]:
X.columns

Index(['SeniorCitizen', 'tenure', 'Male', 'Yes', 'Yes', 'Yes',
       'No phone service', 'Yes', 'Fiber optic', 'No', 'No internet service',
       'Yes', 'No internet service', 'Yes', 'No internet service', 'Yes',
       'No internet service', 'Yes', 'No internet service', 'Yes',
       'No internet service', 'Yes', 'One year', 'Two year', 'Yes',
       'Credit card (automatic)', 'Electronic check', 'Mailed check'],
      dtype='object')